---
title: "writing_functions"
author: "Nhu Nguyen"
date: "2023-11-01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)

```

set seed for reproducibility 
```{r}
set.seed(12345) 

```

### lists 

```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "jeff")

tibble(
  num = vec_numeric,
  char = vec_char
)
```

different stuff with different lengths 

```{r}
vec_numeric = 1:5
vec_char = LETTERS
```

but if we do it as a list 
```{r}
l = 
  list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix = matrix(1:10, nrow = 5, ncol = 2),
    summary = summary(rnorm(100))
  )
```

accessing lists 

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```

### loops 

```{r}
list_norm_samples = 
  list(
    a = rnorm(10, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )

```

mean and sd function

```{r}
mean_and_sd = function(x) { 
  
  if (!is.numeric(x)) {
    stop("argument should be numbers")
  } else if (length(x) < 2) {
    stop("you need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x) 
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
    }
```


```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```

trying to write it as a for loop instead 

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
  
}
```


### use `map`

```{r}
output = map(list_norm_samples, mean_and_sd)

##can use different variables too 

output = map(list_norm_samples, summary)
```






